version: 2
updates:
  # TypeScript ecosystem (TypeScript and types)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typescript-ecosystem:
        patterns:
          - "typescript*"
          - "@types/*"
          - "tslib"

  # Development tools (ESLint, Prettier)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
          - "prettier"

  # Build tools
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      build-tools:
        patterns:
          - "esbuild"
          - "builtin-modules"

  # Core dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      core-deps:
        patterns:
          - "@google/generative-ai"
          - "obsidian"