version: 2
updates:
  # TypeScript ecosystem (TypeScript and types)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
          - "tslib"
      dev-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
          - "prettier"
      build-tools:
        patterns:
          - "esbuild"
          - "builtin-modules"
      core-deps:
        patterns:
          - "@google/generative-ai"
          - "obsidian"